apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: outofthepark15226.azurecr.io/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: gateway-http
            - containerPort: 443
              name: gateway-https
---
apiVersion: v1
kind: Secret
metadata:
   name: secret-tls
data:
   tls.crt: /cacert.pem
   tls.key: /privkey.pem
type: kubernetes.io/tls   
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-deployment
spec:
  ports:
    - name: gateway
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
      paths:
      - path: /
        backend:
          serviceName: gateway-deployment
          servicePort: 443
#    - https:
#        paths:
#        - path: /
#          backend:
#            serviceName: gateway-deployment
#            servicePort: 443
        
      