apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: outofthepark15226.azurecr.io/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: gateway-http