apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: outofthepark15226.azurecr.io/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: gateway-http
            - containerPort: 443
              name: gateway-https
---
apiVersion: v1
kind: Secret
metadata:
   name: secret-tls
type: kubernetes.io/tls
data:
   tls.crt: |
        MIIFuzCCA6OgAwIBAgIUA/lY8PBRrqHrEeTeSP72Ki96kMkwDQYJKoZIhvcNAQELBQAwbTELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVRleGFzMQ8wDQYDVQQHDAZBdXN0aW4xETAPBgNVBAoMCFJldmF0dXJlMRMwEQYDVQQLDApCYTEyMTQyMDIwMRUwEwYDVQQDDAxPdXRPZlRoZVBhcmswHhcNMjEwMjI1MTMwMjIwWhcNMjQwMjI1MTMwMjIwWjBtMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkF1c3RpbjERMA8GA1UECgwIUmV2YXR1cmUxEzARBgNVBAsMCkJhMTIxNDIwMjAxFTATBgNVBAMMDE91dE9mVGhlUGFyazCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKCKFFGbH8b1LTT06GGcHIbMC7CJO7yzevi+iIDHX2DNR4SrigeHOy7UgUTihJqp3T0ZdbakNIO8UilZ2LiTkcVAzvpk8qTDKUrY7ue5mkIFqMkPbXGzTGp6PajOV1UoYuN1V/WnqpDwBJKRrdw6oegrhVSXkB6PgYe3NXZp+CZODUlQeyeyQ7tcd2In0Vp0kBAlu26R6j3md2qx3Tjz7/B4XDfKeUo1iGffydj7RVz4s6miMbKKKo+a05B8EikPGh6U4VhyGo9OtobjMsV08AXSUAWfxP+Z29FiZNvdVmw3sKZvLYt98yjUiqnP3llAh/8YQetC537VVU7U1bOsGubFfJzKokly72548KmNG2PT044o13A4PA9pklEKkzE0L/cJuFGPMSE7PSlGZ28KO8Q0D1D3D/Ro8Yia6HGPdBZBCHm78/zEE6fzIlRUARQ8FVswQMEmcpslgcLLZEyjeXanlzCtQNQjUIP10BLViH7fRz0GJqRh9w3u9tOgBBVMUsQltxJZOm9F3CrH/qGyYNUI8GP7N/gNmVWNKVljdVJUghmTp6v/n92jt6+iKpirbDM9yL8xLR1rQQddNe5X6L1jv4iv/mugrXMcsMjLSW0x3EW8Zfulwg28QVZhVU0YglhIumVdwwLrHDBChzyr58cgLHqWYUv3bnvDa/3PmKVfAgMBAAGjUzBRMB0GA1UdDgQWBBQnyTOtiQBIb4bnawl0ExWsAtEB1TAfBgNVHSMEGDAWgBQnyTOtiQBIb4bnawl0ExWsAtEB1TAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQAuGu1TnlzuXWCDUxBgcsb17DvNL1zaFVdHb/DTvEe6OtATnU/MvmeyLTZfLVcxyKb6rgZkz0Ocy9vIJOYNrFu5FKwRU67IL9hb9+stHOgZPaCvc1H7PtTS4l5UtVRjuR5+/IVSggdEml/zNHtCpk77E9d71lQFvYzFhRbjooAJMFGkIADvcap7LStEfo0uWgcPyztbJa2//t3oMkAzXgwQQ8O6RHNMA/uWIeK459dFzM/f1lEwRcCCqL3N5e/Wl7nyddrz8K3XZpv9pgy2wqnYDkeVv4WzyLV+PyK3hpOzcupuGJddxzu/LW+GvvsczkWQBvlEmL9QZqmXOQ5nadLnQg++Ev5C4/QIL5oxtEz+qoQALrdV4HogYUei+OnGKWSlcX0VGEnFRodYPCKBjYyMuN1GSajPQwGqejygUNxz0pDgCdfTfr/s0voWagw96IAhYe21+/O1xe4NmE244XnaLRSeskELlFVzMHt+TSI7B1EItJsO765BbFxqUG0W53ZHgVMZ41oPaPln1YCYyzuTvNOpUId5HtqgezC4GY89tFnvV/QED6mVVSpjKjzdtQZDViqLnqgXustYtJ6Zk+3K7yRN2Abut+TC3SpGZ4nIIQdPY3axDdeFIPVYAIB+RoNBc63rBVH1nNJcLgCMWvt9knw7FDxdZNnmJJWYgBhh4w==
   tls.key: |
        MIIJKQIBAAKCAgEAoIoUUZsfxvUtNPToYZwchswLsIk7vLN6+L6IgMdfYM1HhKuKB4c7LtSBROKEmqndPRl1tqQ0g7xSKVnYuJORxUDO+mTypMMpStju57maQgWoyQ9tcbNMano9qM5XVShi43VX9aeqkPAEkpGt3Dqh6CuFVJeQHo+Bh7c1dmn4Jk4NSVB7J7JDu1x3YifRWnSQECW7bpHqPeZ3arHdOPPv8HhcN8p5SjWIZ9/J2PtFXPizqaIxsooqj5rTkHwSKQ8aHpThWHIaj062huMyxXTwBdJQBZ/E/5nb0WJk291WbDewpm8ti33zKNSKqc/eWUCH/xhB60LnftVVTtTVs6wa5sV8nMqiSXLvbnjwqY0bY9PTjijXcDg8D2mSUQqTMTQv9wm4UY8xITs9KUZnbwo7xDQPUPcP9GjxiJrocY90FkEIebvz/MQTp/MiVFQBFDwVWzBAwSZymyWBwstkTKN5dqeXMK1A1CNQg/XQEtWIft9HPQYmpGH3De7206AEFUxSxCW3Elk6b0XcKsf+obJg1QjwY/s3+A2ZVY0pWWN1UlSCGZOnq/+f3aO3r6IqmKtsMz3IvzEtHWtBB1017lfovWO/iK/+a6CtcxywyMtJbTHcRbxl+6XCDbxBVmFVTRiCWEi6ZV3DAuscMEKHPKvnxyAsepZhS/due8Nr/c+YpV8CAwEAAQKCAgBPY5kitfyj7fDaJFaalpHA0zzgoyzIZ1Vjlw136aAwBbPdVtseV/CbevkmMIJ03ZWLtoBwvok9sC5NRqIWvNs0WZVBXBRmCCDuY5LZQv6WsafDLf7oYEtkyGifhtLHSP6GDyxdTfnaTOdl9+arZs9UOdloeL8LbdoXXDFzCnptruGBJOySN+SozdQ31QsBmWz4n0AuMLhOvh7Fw4lrta4tE8g+ysDqQsje3Vs7Ex89F7v5Ij1DVnIvq9f9tm1gopg/EU7S5zJdNgarc8VSwj5EEroB3f2UjOiYhfjshWtMfsm7tHUoazOJOHoN+b6yEmhubPeEOQSzwxm5rySzAmQWfHMmvd9ZhFVnawb/c57z9eT7O1g7Pcdc0/nphvHMISkWi/lGWWq0zUOvJTQNBQOIeelqBVZDrjNMFVC8l0na96CB3K5ZhoZOs+NtQbQ8LbJRtABWyg9lW1YzVvgCdEHptbl4sqFf79bzVFwWhmkF3YQF1v1F0GIUDDkk1hixuZVjWk34vj/gid1fiorjoQ8GVMxm/9Jqn+F74praIg782PtxUyK3alSLU4akjEqS228wVOD3dtz53b2jZou2MShmQoSf+v+dV2kfyaGC8DCqYbg4/cuSUSgX2TL+DdW9LR66SQ3QuTixM5jszcP7dCqesOBYnA2ehInD7WvXj6g+wQKCAQEA0IIjyNCDGUIokMxRfN7YYJZPuIrB7GGCJd9zyCRh4xkxDRM6V94OpRJxQHh2xgo+l+gyZknoAi/WsPJrsGcSZWseve90meYnAGwblzXS+X8XJfPKYD2zGJPWVdsVYTHVenTvjBSREQ5j1EW7paWP/JxJYTZ01nxDviKp+vvW6OYTGldGR2Zbh+QNgS5mf9TwJoSr2V6CuW9eaIAF1a5HfWWoEthDHLFY2/sZLKuftWiVlDjbobi2fU+NWuS6jLhL2c+VWMziUyzAzwQjpHtR85+ZYt02vSmytWGnIpdnDOfLaojfhdeYVXdwthVdpBth9FrcIoSM+dCCwQ3lxu0ZoQKCAQEAxRrtpuyo+ezgy7G5oqhmyrq+K+Xo4ibiIw/ZCuRi7zHGTWf1HEkgQI2gnH7bYQtVhmZT+xWlnYtnEtUDekmDBU1TjsomAR6u7Ua3tqkRnRcal2ik05IEXN8FTuQhZnBPVlNsL7ryHsl9cqT6H+Dwvs6Y6G0+sKU+ZidWzzmE8sR/cN3NYQ8NkzBOD88ZrqapLVBNpLu3A8xZCxAOM3Fw8Yn8Hm1k4Zrg4eoR38TKe6RO0k2O1ivcAuM1tmYMyg4UUqklw128l0y+MYMPYVcSPjlt1CWIW09GC3DPxlKTAwCeU5iZYqexzM0yMJixebvM6cpbHDBkc12nr+lKeSNe/wKCAQEAoiJgUxoYpz5zrszCHLhoRwr66MQ1MWtNOcf9D0eDOoVvR/yIpKTOfHvPxtMlgK+cpqDu9+1GVNUAO832AVDU1DosyIL4B2gZMdHezoETEeFKjb95wcaYimcDBvX6NP78QmHFmAayGzI2XGzxEkigo0ygHtCqn9I3FxV7WegU4Dtv5U6yHnkweYXTHn2HRKW/LCSEQN2mBy3bmqTaZKNFgfPXcvfpj9k0ALLLi5nU8cpmbcCcwK+Sb/S5NVGg4iW5DaDGQCvpXcXyE8fjM1aVjjyvmFnt48AV78cEoPhcMIPaAHh4X2obUXI0GdKZYy/LxqgUf17VBLinxBjbcQkToQKCAQA4WvSsD2pY2wOC+fOrsB6DxFTvVDL7xkZN5BAYbyhiX4blRt3sEnRoQJY1aIfs/UKcxNEqLwxFOUBlQAZYhoAxmeRUJTQsictWCCwqy7g/hAWUWNUXsN4Sd6ma3ts14NKuSffaxcbISq/VgZoKV1Q+Ge/aNLIB650ltAW8BiQfDVOqv6AjKhylguAu4PXk273vONCaUxmGunyTDyogR0UVqnAtevWnE5NMxJILusZyB46JzqcSUUP8h14qIo9xjgj9gWNMspZjZAvVODXDjROoOt9OEtUj1kyepMijWaSy7RBXsn/Ylz3c4qaBAodr2OhDyBm4u5Vc7uAtCbTDYfudAoIBAQCKmmyrDGipq04k3nwQVCgCCeUPvh7PUVl9oqwogsB6nkkdhCE6XvAytHLHy5OEa+avelWBho9nyGnnJtvDQDcB3BBQAbrMiigUsoqId7VgqkDytwzoo8pOZy+tw2x/M5CcviByMwJ9SIUK6Iq6kk+AAruQU5YaDPSuuI8tpqiUst28GkRRhycT77PYPGizEnba+KgEuF+1vBG8ZEWbx07tPeu6AA+QQnRu0KaqpI2Nh3Jej8koT4Rq4NzWfHTRZwuON+Jx7Mq3WcI5eE99hPDHZK67sK/gDgO3yHouUpYKCEU80DoHl2T+Z8xWQnIB1H6QgNlvS1DbzCuez5p0FP8y
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-deployment
spec:
  ports:
    - name: gateway
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
      - path: /
        backend:
          serviceName: gateway-deployment
          servicePort: 443
#    - https:
#        paths:
#        - path: /
#          backend:
#            serviceName: gateway-deployment
#            servicePort: 443