apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: outoftheparkacr.azurecr.io/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 80 
              name: http
            - containerPort: 443
              name: https
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: gateway-deployment
spec:
  ports:
#    - name: http
#      protocol: TCP
#      port: 80
#      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: gateway
  type: ClusterIP
